Debug S05_FunctionTest(12)
; Debug S05_FunctionTrisTest()
; Debug S05_FunctionBis()
; MessageRequester("Title : "+ S05_FunctionBis(), "Message : "+ S05_FunctionBis())
; Debug S05_FunctionBis()
; Debug S05_FunctionTrisTest()
; Debug S05_FunctionBis()
